# Generated by Django 2.2.4 on 2019-10-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0002_auto_20191009_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=32, unique=True),
        ),
    ]
