# Generated by Django 2.2.4 on 2019-10-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0004_article_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='IndexLinks',
        ),
    ]
