# Generated by Django 2.2.4 on 2019-10-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0006_auto_20191010_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indexlink',
            new_name='Indexlinks',
        ),
    ]
