# Generated by Django 2.2.4 on 2019-10-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0007_auto_20191010_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indexlinks',
            new_name='Indexlink',
        ),
    ]
